query GetScores {
  allScores {
    id
    date
    name
    score
  }
}

query GetUniqueScores {
  allScoresUniqueUser {
    id
    date
    name
    score
  }
}

query GetScoresPastWeek {
  allScoresPastWeek {
    id
    date
    name
    score
  }
}

query GetScoresPastDay {
  allScoresPastDay {
    id
    date
    name
    score
  }
}

mutation PostScore($score: Int!, $name: String!) {
  createScore(score: { name: $name, score: $score }) {
    date
    id
    name
    score
  }
}
