query GetRegularScores {
  allScores {
    id
    date
    name
    score
  }
  allScoresUniqueUser {
    id
    date
    name
    score
  }
  allScoresPastWeek {
    id
    date
    name
    score
  }
  allScoresPastDay {
    id
    date
    name
    score
  }
}

mutation PostScore($score: Int!, $name: String!) {
  createScore(score: { name: $name, score: $score }) {
    date
    id
    name
    score
  }
}

query GetDailyQuestions {
  getDailyQuestions {
    lhs
    operator
    rhs
  }
}

mutation StartDaily {
  startDaily
}

mutation EndDaily($key: String!, $duration: Int!) {
  submitDaily(key: $key, milliseconds: $duration)
}

query DailyChallengeResults {
  getDailyScores {
    user {
      username
    }
    ms
    date
  }
}
