name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
     - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Type Check
        run: npx nx affected --target=typecheck

      - name: Format
        run: npx nx format:check --verbose

      - name: Lint
        run: npx nx affected --target=lint

      - name: Test
        run: npx nx affected --target=test --ci --code-coverage
